import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HomeWrapper from "@/components/wrappers/HomeWrapper";
import ReduxProvider from "@/redux/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <HomeWrapper>{children}</HomeWrapper>
        </ReduxProvider>
      </body>
    </html>
  );
}
